name: khoaluantotnghiep2021
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  #google_fonts: ^2.0.0
  # State & Navigation Management
  get: ^3.26.0
  # UI widget package
  badges: ^1.1.6
  bubble_bottom_bar: ^1.2.0
  #utils
  dio: ^3.0.10
  socket_io_client: ^0.9.12
  shared_preferences: ^0.5.12+4
  rx_shared_preferences: ^1.3.3
  flutter_time_picker_spinner: ^1.0.6+1
  webview_flutter: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  assets:
    - assets/images/

